import { PolicyLayout } from '@/components/policies/PolicyLayout';

export default function TermsPage() {
  return (
    <PolicyLayout title="Terms & Conditions" updatedAt="April 28, 2026">
      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-slate-900">Electronic Record Notice</h2>
        <p>
          This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder, as
          applicable, including amended provisions relating to electronic records in various statutes. This electronic record
          is generated by a computer system and does not require physical or digital signatures.
        </p>
      </section>
      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-slate-900">Platform Information</h2>
        <p>
          This document is published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines)
          Rules, 2011, requiring publication of rules and regulations, privacy policy and Terms of Use for access or usage of
          domain name https://eyeshop.in/ (&ldquo;Website&rdquo;), including related mobile site and mobile application (collectively,
          the &ldquo;Platform&rdquo;).
        </p>
        <p>
          The Platform is owned by Eye-Hyve Technologies Private Limited, a company incorporated under the Companies Act, 1956
          with its registered office at No. 16, Shop No. 2, 7th Cross Road, 6th Main, Narayana Gowda Layout, BTM Layout 1st
          Stage, Tavarekere, Bengaluru, Karnataka 560029 (hereinafter referred to as &ldquo;Platform Owner&rdquo;, &ldquo;we&rdquo;,
          &ldquo;us&rdquo;, &ldquo;our&rdquo;).
        </p>
      </section>
      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-slate-900">Acceptance of Terms</h2>
        <p>
          Your use of the Platform and services and tools are governed by the following terms and conditions (&ldquo;Terms of
          Use&rdquo;), including applicable policies incorporated herein by reference. If you transact on the Platform, you shall
          be subject to policies applicable to the Platform for such transaction. By mere use of the Platform, you contract
          with the Platform Owner and these terms and policies constitute binding obligations.
        </p>
        <p>
          These Terms of Use relate to your use of our website, goods (as applicable), or services (as applicable)
          (collectively, &ldquo;Services&rdquo;). Any additional or conflicting terms proposed by you are expressly rejected by the
          Platform Owner.
        </p>
        <p>
          These Terms may be modified at any time without assigning any reason. It is your responsibility to periodically
          review these Terms to stay informed of updates.
        </p>
        <p>
          For the purpose of these Terms, &ldquo;you&rdquo;, &ldquo;your&rdquo;, or &ldquo;user&rdquo; shall mean any natural or legal person who has agreed
          to become a user / buyer on the Platform.
        </p>
        <p className="font-semibold text-slate-900">
          ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER
          THESE TERMS OF USE. PLEASE READ THESE TERMS CAREFULLY BEFORE PROCEEDING.
        </p>
      </section>
      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-slate-900">Terms of Use</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            To access and use the Services, you agree to provide true, accurate, and complete information during and after
            registration, and you are responsible for all acts done through your registered account.
          </li>
          <li>
            Neither we nor any third parties provide warranty or guarantee as to the accuracy, timeliness, performance,
            completeness, or suitability of information and materials offered on this website or through the Services for any
            specific purpose. Such information may contain inaccuracies or errors, and we exclude liability for the same to the
            fullest extent permitted by law.
          </li>
          <li>
            Your use of the Platform and Services is solely at your own risk and discretion, and you must independently assess
            whether the Services meet your requirements.
          </li>
          <li>
            The contents of the Platform and Services are proprietary to us and/or licensed to us. You shall have no authority
            to claim intellectual property rights, title, or interest in such content, including design, layout, look, and
            graphics.
          </li>
          <li>Unauthorized use of the Platform and/or Services may lead to action under these Terms and applicable laws.</li>
          <li>You agree to pay charges associated with availing the Services.</li>
          <li>
            You agree not to use the Platform and/or Services for any unlawful, illegal, or prohibited purpose under these
            Terms or Indian/local laws.
          </li>
          <li>
            The Platform and Services may contain links to third-party websites. Access to such links is governed by third-party
            policies and terms, and such links are provided for convenience and additional information.
          </li>
          <li>
            Upon initiating a transaction for availing the Services, you enter into a legally binding and enforceable contract
            with the Platform Owner.
          </li>
          <li>
            You shall indemnify and hold harmless the Platform Owner, its affiliates, group companies, officers, directors,
            agents, and employees from claims, demands, actions, penalties, and reasonable attorney fees arising from your
            breach of these Terms, Privacy Policy, other policies, or violation of law or third-party rights (including
            intellectual property rights).
          </li>
          <li>
            Notwithstanding anything contained in these Terms, parties shall not be liable for failure to perform obligations if
            such performance is prevented or delayed by a force majeure event.
          </li>
        </ul>
      </section>
      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-slate-900">Governing Law and Jurisdiction</h2>
        <p>
          These Terms and any dispute or claim relating to them, including enforceability, shall be governed by and construed
          in accordance with the laws of India.
        </p>
        <p>
          All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the
          courts in Andhra Pradesh.
        </p>
      </section>
      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-slate-900">Contact</h2>
        <p>
          All concerns or communications relating to these Terms must be communicated using the contact information provided on
          this website.
        </p>
      </section>
    </PolicyLayout>
  );
}
